#
# This source file is part of the Stanford Spezi open-source project
#
# SPDX-FileCopyrightText: 2024 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test Notebook
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
    - name: Setup NodeJS
      uses: actions/setup-node@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'
    - name: Setup LaTex
      run: |
        sudo apt-get install pandoc texlive-xetex texlive-fonts-recommended texlive-plain-generic
    - name: Cache Firebase Emulators
      uses: actions/cache@v3
      with:
        path: ~/.cache/firebase/emulators
        key: ${{ runner.os }}-${{ runner.arch }}-firebase-emulators-${{ hashFiles('~/.cache/firebase/emulators/**') }}
    - name: Install Firebase CLI Tools
      run: npm install -g firebase-tools
    - name: Install Infrastructure
      run: |
        python -m pip install --upgrade pip
        pip install jupyterlab
    - name: Install SpeziDataPipelineTemplate Dependencies
      run: |
        pip install pandas numpy matplotlib firebase-admin requests ipywidgets pytz
<<<<<<< HEAD
    - name: Conditionally Run Firebase Emulator & Execute Notebook
      run: |
        if [ "${{ env.CI }}" = "true" ]; then
          echo "CI environment detected, importing data from sample_data/ and executing notebook."
          firebase emulators:exec --import=./sample_data "jupyter nbconvert --to pdf --execute SpeziDataPipelineTemplate.ipynb"
        else
          echo "Not a CI environment, executing notebook without importing data."
          jupyter nbconvert --to pdf --execute SpeziDataPipelineTemplate.ipynb
        fi
=======
    - name: Run Firebase Emulator & Execute Notebook
      run: |
        firebase emulators:exec "jupyter nbconvert --to pdf --execute SpeziDataPipelineTemplate.ipynb"
>>>>>>> 51e212a... Improve Badge & Add Basic GitHub Actions (#4)
    - uses: actions/upload-artifact@v4
      with:
        name: SpeziDataPipelineTemplate.pdf
        path: SpeziDataPipelineTemplate.pdf
