#
# This source file is part of the Stanford Spezi open-source project
#
# SPDX-FileCopyrightText: 2024 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test Notebook
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
    - name: Cache Firebase Emulators
      if: ${{ !env.selfhosted && inputs.setupfirebaseemulator }}
      uses: actions/cache@v3
      with:
        path: ~/.cache/firebase/emulators
        key: ${{ runner.os }}-${{ runner.arch }}-firebase-emulators-${{ hashFiles('~/.cache/firebase/emulators/**') }}
    - name: Setup NodeJS
      uses: actions/setup-node@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'
    - name: Install Firebase CLI Tools
      run: npm install -g firebase-tools
    - name: Install Infrastructure
      run: |
        python -m pip install --upgrade pip
        pip install jupyterlab
    - name: Install SpeziDataPipelineTemplate Dependencies
      run: |
        pip install pandas numpy matplotlib firebase-admin requests ipywidgets pytz
    - name: Run Firebase Emulator & Execute Notebook
      run: |
        firebase emulators:exec "jupyter nbconvert --to pdf --execute Untitled.ipynb"
    - uses: actions/upload-artifact@v4
      with:
        name: SpeziDataPipelineTemplate.pdf
        path: SpeziDataPipelineTemplate.pdf
